name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'

jobs:

  jdk_8_maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean verify --fae
        working-directory: jdk_8_maven
