name: CI

on:
  push:
    branches-ignore:
      - 'master'  # issue with dependency with EvoMaster releases
    tags-ignore:
      - '**'

jobs:

  docker-build:
    # this one doesn't use EvoMaster drivers by default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WFD
        uses: actions/checkout@v6
      - name: Build All With Docker
        run: python scripts/dist-docker.py

  direct-builds:
    needs: docker-build
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        folder: [jdk_8_maven, jdk_11_maven, jdk_17_maven, jdk_21_maven, jdk_8_gradle, jdk_11_gradle, jdk_17_gradle]
        include:
          # Maven
          - folder: jdk_8_maven
            jdk-version: 8
            command: mvn clean install -DskipTests
          - folder: jdk_11_maven
            jdk-version: 11
            command: mvn clean install -DskipTests
          - folder: jdk_17_maven
            jdk-version: 17
            command: mvn clean install -DskipTests
          - folder: jdk_21_maven
            jdk-version: 21
            command: mvn clean install -DskipTests
          # Gradle
          - folder: jdk_8_gradle
            jdk-version: 8
            command: chmod +x gradlew & ./gradlew build -x test
          - folder: jdk_11_gradle
            jdk-version: 11
            command: chmod +x gradlew & ./gradlew build -x test
          - folder: jdk_17_gradle
            jdk-version: 17
            command: chmod +x gradlew & ./gradlew build -x test
    steps:
      - name: Setup JDK for EvoMaster
        uses: actions/setup-java@v5
        with:
          # client library is on 8, but, to build whole EM, need higher.
          java-version: 17
          distribution: 'zulu'
      - name: Checkout EvoMaster
        uses: actions/checkout@v6
        with:
          repository: WebFuzzing/EvoMaster
          path: evomaster
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install EvoMaster root pom.xml
        run: mvn -N clean install -DskipTests
        working-directory: evomaster
      - name: Install EvoMaster client-java
        run: mvn clean install -DskipTests
        working-directory: evomaster/client-java
      - name: Setup JDK for WFD
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'zulu'
      - name: Checkout WFD
        uses: actions/checkout@v6
      - name: Build WFD
        run: ${{ matrix.command }}
        working-directory: ${{ matrix.folder }}
